### ISSUE TITLE
safety_controller.lower(/upper) not guaranteed to exist

### ISSUE THREAD

**Issue by goretkin** [gt-ros-pkg/hrl-kdl#5]
When trying to use my PR2 URDF, the block here https://github.com/gt-ros-pkg/hrl-kdl/blob/hydro/pykdl_utils/src/pykdl_utils/kdl_kinematics.py#L90 raises

```
AttributeError: 'SafetyController' object has no attribute 'lower'
```

Indeed it doesn't appear that these XML elements don't seem to be required according to http://wiki.ros.org/urdf/XML/joint

**Comment by mrich7** [comment]
This has been fixed. The error seemed to be that the safety_controller tag has the attribute 'soft_lower_limit' instead of 'lower'. The attribute 'soft_lower_limit' is optional (http://wiki.ros.org/urdf/XML/joint), but the line you referenced shouldn't cause any problems now.
