### ISSUE TITLE
length check in joint_state callback

### ISSUE THREAD

**Issue by goretkin** [gt-ros-pkg/hrl-kdl#6]
From https://github.com/gt-ros-pkg/hrl-kdl/blob/hydro/pykdl_utils/src/pykdl_utils/joint_kinematics.py#L146

``` python
    # Joint angles listener callback
    def _joint_state_cb(self, msg):
        if False and self._joint_state_inds is None:
            joint_names_list = self.get_joint_names()
            self._joint_state_inds = [msg.name.index(joint_name) for 
                                     joint_name in joint_names_list]
        if len(msg.position) == len(self._joint_state_inds):
            self._joint_angles = [msg.position[i] for i in self._joint_state_inds]
        if len(msg.velocity) == len(self._joint_state_inds):
            self._joint_velocities = [msg.velocity[i] for i in self._joint_state_inds]
        if len(msg.effort) == len(self._joint_state_inds):
            self._joint_efforts = [msg.effort[i] for i in self._joint_state_inds]
```

I think the length checks are incorrect. In my case I'm trying to get kinematics for only one arm, so the `/joint_state` topic publishes many joints, but `len(self._joint_state_inds)` is 7.

(Also if I'm not mistaken, the joint_state publisher is at liberty to reorder the joints from one iteration to the next, so perhaps it is safest to re-establish the joint indices on each message)

**Comment by mrich7** [comment]
This has been fixed. Length checks were removed.

**Comment by goretkin** [comment]
For reference: https://github.com/gt-ros-pkg/hrl-kdl/commit/969dac2000799f319db5bea8e77cc77f92a97c39
